## Lab 2
#### Variant 13

In [126]:
import math
import random

import numpy as np

##### 1.The number n is entered. Output an array of size n×n, in<br>on which the numbers from 1 to n go along the diagonal, and the other numbers are equal to 0.

In [127]:
# NumPy
def task_1(n):
    matrix = np.zeros((n, n))
    np.fill_diagonal(matrix, np.arange(1, n + 1))
    return matrix


task_1(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.]])

In [128]:
# Iterative
def task_1(n):
    return [[i if i == j else 0 for j in range(1, n + 1)] for i in range(1, n + 1)]


task_1(10)

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 3, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 6, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 7, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 8, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 9, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 10]]

##### 6.An array is entered from the keyboard. Replace all zeros elements at –1.

In [129]:
# NumPy
def task_7(array):
    arr = np.array(array)
    arr[arr == 0] = -1
    return arr


task_7([1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 11, 12, 13, 0, 14, 15, 16, 17, 0, 18, 19, 20, 0])

array([ 1,  2,  3, -1,  4,  5,  6, -1,  7,  8,  9, -1, 11, 12, 13, -1, 14,
       15, 16, 17, -1, 18, 19, 20, -1])

In [130]:
# Iterative
def task_7(array):
    for i in range(len(array)):
        if array[i] == 0:
            array[i] = -1
    return array


task_7([1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 11, 12, 13, 0, 14, 15, 16, 17, 0, 18, 19, 20, 0])

[1,
 2,
 3,
 -1,
 4,
 5,
 6,
 -1,
 7,
 8,
 9,
 -1,
 11,
 12,
 13,
 -1,
 14,
 15,
 16,
 17,
 -1,
 18,
 19,
 20,
 -1]

##### 8.An array is entered from the keyboard. Calculate in it the number of zero and non-zero elements.

In [131]:
# NumPy
def task_8(array):
    arr = np.array(array)
    non = np.count_nonzero(arr)
    zero = arr.size - non
    return non, zero


task_8([1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 11, 12, 13, 0, 14, 15, 16, 17, 0, 18, 19, 20, 0])

(19, 6)

In [132]:
# Iterative
def task_8(array):
    non = 0
    zero = 0
    for i in range(len(array)):
        if array[i] == 0:
            zero = zero + 1
        else:
            non = non + 1
    return non, zero


task_8([1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 11, 12, 13, 0, 14, 15, 16, 17, 0, 18, 19, 20, 0])

(19, 6)

##### 11.Create an array of units of size n×n and add to it is a "frame" formed from 0.

In [133]:
# NumPy
def task_11(n):
    matrix = np.ones((n, n))
    return np.pad(matrix, pad_width=1, mode='constant', constant_values=0)


task_11(10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
# Iterative
def task_11(n):
    matrix = [[1 for _ in range(n)] for _ in range(n)]

    matrix.insert(0, [0 for _ in range(n)])
    matrix.append([0 for _ in range(n)])

    for i in range(n + 2):
        matrix[i].insert(0, 0)
        matrix[i].append(0)

    return matrix


task_11(10)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

#### 14.Place zeros and ones in a chessboard on the 8×8 field order.

In [135]:
# NumPy
def task_14():
    array = ([0, 1, 0, 1, 0, 1, 0, 1],
             [1, 0, 1, 0, 1, 0, 1, 0])
    matrix = np.tile(array, (4, 1))
    return matrix


task_14()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [136]:
# Iterative
def task_14():
    matrix = [[0 for _ in range(8)] for _ in range(8)]
    for i in range(8):
        for j in range(8):
            if i % 2 == 0 and j % 2 != 0:
                matrix[i][j] = 1
            if i % 2 != 0 and j % 2 == 0:
                matrix[i][j] = 1

    return matrix


task_14()

[[0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0]]

#### 16. Fill the vector with values from 0 to n. All values, that are greater than 3n/4 and less than n/4 should be replaced by zeros.

In [137]:
#NumPy
def task_16(n):
    array = np.arange(n + 1)
    array[:math.ceil(n / 4)] = 0
    array[math.ceil(3 * n / 4):] = 0
    return array


task_16(10)

array([0, 0, 0, 3, 4, 5, 6, 7, 0, 0, 0])

In [138]:
#Iterative
def task_16(n):
    return [0 if (i < n / 4 or i > 3 * n / 4) else i for i in range(n + 1)]

task_16(10)

[0, 0, 0, 3, 4, 5, 6, 7, 0, 0, 0]

#### 17. Fill the vector with values from 0 to n. Replace signs for all values less than n/2 and greater than 3n/4 on opposites

In [139]:
#NumPy
def task_17(n):
    array = np.arange(n + 1)
    array[:math.ceil(n / 2)] *= -1
    array[math.ceil(3 * n / 4):] *= -1
    return array


task_17(10)


array([  0,  -1,  -2,  -3,  -4,   5,   6,   7,  -8,  -9, -10])

In [140]:
#Iterative
def task_17(n):
    return [-i if (i < n / 2 or i > 3 * n / 4) else i for i in range(n + 1)]


task_17(10)

[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]

#### 18. Generate a vector of n random numbers in a range from 0 to 99. Determine the number of unique numbers in the sequence.

In [141]:
#NumPy
def task_18(n):
    return len(np.unique(np.random.randint(0, 100, n)))


task_18(100)

71

In [142]:
#Iterative
def task_18(n):
    return len(set([random.randrange(0, 100) for i in range(n)]))


task_18(100)

63

## Task 2
### Solving system of linear equations with Cramer's rule
<img src="img.png">

In [143]:
matrix = np.array([[5, 1, -1, 0],
                   [3, -3, 1, 4],
                   [3, -2, 1, 0],
                   [1, -4, 1, 0]])

results = np.array([-9, -7, -16, 0])


def cramer(matrix, results):
    det = np.linalg.det(matrix)
    size = matrix.shape[0]

    if np.allclose(det, 0):
        print("Determinant is zero, aborting.")
        return 0

    solution = np.zeros(size)

    for i in range(size):
        temp_matrix = np.copy(matrix)
        temp_matrix[:, i] = np.copy(results)
        solution[i] = np.linalg.det(temp_matrix) / det

    return solution


cramer = cramer(matrix, results)
print(f"Simple result: {cramer}")

numpy = np.linalg.solve(matrix, results)
print(f"NumPy result: {numpy}\n")
assert np.allclose(numpy, cramer)

multiplication = np.dot(matrix, cramer)
print("matrix multiplication: ")
print(f"Expected {results}")
print(f"Result {multiplication}\n")
assert np.allclose(results, multiplication)

inverse = np.dot(np.linalg.inv(matrix), results)
print("inverse matrix: ")
print(f"Expected {inverse}")
print(f"Result {cramer}\n")
assert np.allclose(inverse, cramer)

Simple result: [ -3.66666667  -4.33333333 -13.66666667   1.16666667]
NumPy result: [ -3.66666667  -4.33333333 -13.66666667   1.16666667]

matrix multiplication: 
Expected [ -9  -7 -16   0]
Result [-9.00000000e+00 -7.00000000e+00 -1.60000000e+01 -7.10542736e-15]

inverse matrix: 
Expected [ -3.66666667  -4.33333333 -13.66666667   1.16666667]
Result [ -3.66666667  -4.33333333 -13.66666667   1.16666667]



## Task 3
### Evaluating matrix expression
<img src="img_2.png"><br>
<strong>Expression :</strong><br>
<img src="expression.png">


In [144]:
A = [[1, -2, 3],
     [2, 3, 5],
     [1, 4, -1]]

A_np = np.array(A)

B = [[4, 11, 3],
     [1, 6, 1],
     [2, 2, 16]]

B_np = np.array(B)


def mmult(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_cols != b_rows:
        return []

    return [[sum([x * y for (x, y) in zip(row, col)]) for col in zip(*B)] for row in A]


def madd(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_rows != b_rows or a_cols != b_cols:
        return []

    return [[A[i][j] + B[i][j] for j in range(a_cols)] for i in range(a_rows)]


def msub(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_rows != b_rows or a_cols != b_cols:
        return []

    return [[A[i][j] - B[i][j] for j in range(a_cols)] for i in range(a_rows)]


def smult(scalar, matrix):
    rows, cols = len(matrix), len(matrix[0])
    return [[matrix[i][j] * scalar for j in range(cols)] for i in range(rows)]


def solve_numpy():
    return (A_np - B_np @ B_np) @ (2 * A_np + B_np)


def solve_iterative():
    return mmult(msub(A, mmult(B, B)), madd(smult(2, A), B))

result_numpy = solve_numpy()
result_iterative = solve_iterative()

print("NumPy:", result_numpy)
print("Iterative:", result_iterative)
print("Equal:", np.allclose(result_numpy, result_iterative))

NumPy: [[-1054 -2320 -2538]
 [ -370  -822  -876]
 [-1616 -3681 -4761]]
Iterative: [[-1054, -2320, -2538], [-370, -822, -876], [-1616, -3681, -4761]]
Equal: True
